---
- name: Create NPM directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: "{{ docker_user }}"
    group: "{{ docker_group }}"
    mode: '0755'
  loop:
    - "{{ npm_volume_data }}"

- name: Deploy NPM Compose file
  ansible.builtin.template:
    src: npm-compose.yml.j2
    dest: /srv/docker/npm/docker-compose.yml
    owner: "{{ docker_user }}"
    group: "{{ docker_group }}"
    mode: '0644'

- name: Start NPM container
  ansible.builtin.command:
    cmd: docker compose up -d
    chdir: /srv/docker/npm
