---
- name: Create Omada directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: "{{ docker_user }}"
    group: "{{ docker_group }}"
    mode: '0755'
  loop:
    - "{{ omada_volume_data }}"

- name: Deploy Omada Compose file
  ansible.builtin.template:
    src: omada/omada-compose.yml.j2
    dest: /srv/docker/omada/docker-compose.yml
    owner: "{{ docker_user }}"
    group: "{{ docker_group }}"
    mode: '0644'

- name: Start Omada container
  ansible.builtin.command:
    cmd: docker compose up -d
    chdir: /srv/docker/omada