---
- name: Create Portainer deployment directory
  ansible.builtin.file:
    path: "{{ portainer_deploy_dir }}"
    state: directory
    owner: "{{ docker_user }}"
    group: "{{ docker_group }}"
    mode: '0755'

- name: Deploy Portainer Compose file
  ansible.builtin.template:
    src: portainer-compose.yml.j2
    dest: "{{ portainer_deploy_dir }}/docker-compose.yml"
    owner: "{{ docker_user }}"
    group: "{{ docker_group }}"
    mode: '0644'

- name: Start Portainer container
  ansible.builtin.command:
    cmd: docker compose up -d
    chdir: "{{ portainer_deploy_dir }}"

