---
- name: Basic setup for Debian servers
  hosts: debian_servers
  become: yes

  vars_files:
    - ../vault/secret.yml

  roles:
    - ../roles/common
    - ../roles/bare-metal
    - ../roles/docker